spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: subscribe-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    topic:
      weather: weather.service
      telegram: telegram.service
      subscribe: subscribe.service
  data:
    mongodb:
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      authentication-database: ${DB_AUTH:admin}
      database: ${DB_NAME:subscribe-service}